[package]
name = "deltae"
version = "0.1.1"
authors = ["Ryan O'Beirne <robeirne@spoonflower.com>"]
description = "Calculate Delta E between two colors in CIE Lab space."
edition = "2018"

[dependencies]
clap = "2.32.0"
